name: 'SaberPlaceholder'
version: '1.0.0'
api-version: '1.19'
author: 'UnfamousThomas'
main: me.unfamousthomas.saberplaceholder.SaberPlaceHolder
depend:
  - Factions
  - PlaceholderAPI
description: Adds a few placeholders to use for factions (using placeholderapi).
